import { isGroup, renderSidebar, sidebarEntries } from "./sidebar.js";
import { customCss } from "./theme.js";
import { siteStrings } from "./site-strings.js";
import { STRUCTURE_SLUG } from "./structure.js";
import type { SidebarNode } from "./sidebar.js";
import type { SiteStats } from "./structure.js";

/** Pinned so that ejecting twice a month apart produces the same project. */
const VERSIONS = {
  astro    : "^7.2.10",
  starlight: "^0.41.11",
  sharp    : "^0.35.4",
};

/** How many shortcuts the landing page offers before it stops being a shortcut. */
const MAX_ACTIONS = 3;

const CUSTOM_CSS = "src/styles/custom.css";

export const packageName = (title: string): string => {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug === "" ? "docs-site" : `${slug}-docs`;
};

export interface TemplateInput {
  title       : string;
  description?: string | undefined;
  accent      : string;
  /** The documentation's language, which is what the site speaks. */
  lang        : string;
  stats       : SiteStats;
  /** Where "Get started" lands. Falls back to the first page of the sidebar. */
  startSlug  ?: string | undefined;
  sidebar     : readonly SidebarNode[];
}

const packageJson = (input: TemplateInput): string =>
  `${JSON.stringify(
    {
      name   : packageName(input.title),
      type   : "module",
      version: "0.0.1",
      private: true,
      scripts: {
        dev    : "astro dev",
        build  : "astro build",
        preview: "astro preview",
      },
      dependencies: {
        "@astrojs/starlight": VERSIONS.starlight,
        astro               : VERSIONS.astro,
        sharp               : VERSIONS.sharp,
      },
    },
    null,
    2,
  )}\n`;

const astroConfig = (input: TemplateInput): string =>
  `import starlight from "@astrojs/starlight";
import { defineConfig } from "astro/config";

// Generated by \`glossic eject\`. The sidebar mirrors the glossic manifest: the
// directory hierarchy the project actually has, in the order the manifest
// lists it. The accent is set once in ${CUSTOM_CSS}.
export default defineConfig({
  integrations: [
    starlight({
      title: ${JSON.stringify(input.title)},${
        input.description === undefined
          ? ""
          : `\n      description: ${JSON.stringify(input.description)},`
      }
      customCss: ["./${CUSTOM_CSS}"],
      sidebar: ${renderSidebar(input.sidebar)},
    }),
  ],
});
`;

/** Astro 5 and up load a collection through a loader declared here. */
const contentConfig = (): string =>
  `import { docsLoader } from "@astrojs/starlight/loaders";
import { docsSchema } from "@astrojs/starlight/schema";
import { defineCollection } from "astro:content";

export const collections = {
  docs: defineCollection({ loader: docsLoader(), schema: docsSchema() }),
};
`;

/**
 * The shortcuts the landing page offers: the first page of each top-level
 * section, which is what a reader arriving with no idea of the shape of the
 * project needs. A lone page is its own shortcut. The structure page is left
 * out; the primary button already goes somewhere better.
 */
const sectionActions = (nodes: readonly SidebarNode[]): Array<{ text: string; link: string }> =>
  nodes
    .filter((node) => isGroup(node) || node.slug !== STRUCTURE_SLUG)
    .map((node) => {
      if (!isGroup(node)) return { text: node.label, link: `/${node.slug}/` };

      const first = sidebarEntries(node.items)[0];

      return first === undefined ? undefined : { text: node.label, link: `/${first.slug}/` };
    })
    .filter((action): action is { text: string; link: string } => action !== undefined)
    .slice(0, MAX_ACTIONS);

/** The first real page of the sidebar, for when nobody named a better one. */
const firstPage = (nodes: readonly SidebarNode[]): string | undefined =>
  sidebarEntries(nodes).find((entry) => entry.slug !== STRUCTURE_SLUG)?.slug;

/**
 * Starlight's splash layout: no sidebar, no table of contents, the name of the
 * thing, one way in, and enough of the manifest for a reader to know what they
 * are looking at before they click anything.
 */
const landingPage = (input: TemplateInput): string => {
  const s       = siteStrings(input.lang);
  const start   = input.startSlug ?? firstPage(input.sidebar);
  const tagline = input.description ?? `Documentation for ${input.title}, generated from the code.`;

  const lines = [
    "---",
    `title: ${JSON.stringify(input.title)}`,
    `description: ${JSON.stringify(tagline)}`,
    "template: splash",
    "hero:",
    `  tagline: ${JSON.stringify(tagline)}`,
    "  actions:",
  ];

  if (start !== undefined) {
    lines.push(
      `    - text: ${JSON.stringify(s.getStarted)}`,
      `      link: ${JSON.stringify(`/${start}/`)}`,
      "      icon: right-arrow",
      "      variant: primary",
    );
  }

  lines.push(
    `    - text: ${JSON.stringify(s.structure)}`,
    `      link: ${JSON.stringify(`/${STRUCTURE_SLUG}/`)}`,
    "      icon: document",
    "      variant: minimal",
  );

  // The page "Get started" already points at is not offered a second time.
  const rest = sectionActions(input.sidebar).filter(
    (action) => start === undefined || action.link !== `/${start}/`,
  );

  for (const action of rest.slice(0, MAX_ACTIONS - 1)) {
    lines.push(
      `    - text: ${JSON.stringify(action.text)}`,
      `      link: ${JSON.stringify(action.link)}`,
      "      icon: right-arrow",
      "      variant: minimal",
    );
  }

  const languages = input.stats.languages
    .slice(0, 4)
    .map((entry) => `${entry.language} ${entry.count}`)
    .join(", ");

  lines.push(
    "---",
    "",
    `## ${s.atAGlance}`,
    "",
    `- **${input.stats.units}** ${s.modules}${input.stats.projects > 1 ? ` · **${input.stats.projects}** ${s.project.toLowerCase()}s` : ""}`,
    `- **${input.stats.files}** ${s.files.toLowerCase()}`,
    `- ${s.languages}: ${languages === "" ? "-" : languages}`,
    `- ${s.generated}: ${input.stats.generatedAt.slice(0, 10)}`,
    "",
    "Every page here was written from the code it documents, and carries the",
    "hash of what it was written from. When the code moves, `glossic check` says",
    "which page fell behind.",
    "",
  );

  return lines.join("\n");
};

const readme = (input: TemplateInput): string =>
  `# ${input.title} documentation

Generated by [glossic](https://github.com/rody-huancas/glossic). This is a plain
Astro + Starlight project: nothing here depends on glossic at runtime.

## Run it

\`\`\`bash
npm install
npm run dev      # http://localhost:4321
npm run build    # static site in dist/
\`\`\`

## Inside a monorepo

This site is a project of its own, not a package of whatever surrounds it, and
\`pnpm-workspace.yaml\` is what says so. pnpm resolves a workspace by walking up
to the first one of those it finds, so without it a site generated inside a
pnpm monorepo is read as one of that monorepo's packages: \`pnpm install\` run
from here installs nothing at all, and \`pnpm run dev\` then finds no astro.

Delete that file if you would rather the site belonged to the surrounding
workspace, and add this directory to that workspace's own \`packages:\` list.

## Making it yours

- **Colours** live in \`${CUSTOM_CSS}\`, as Starlight's own variables. Change one
  and the whole site follows.
- **The landing page** is \`src/content/docs/index.mdx\`. It is written once and
  never overwritten, so edit it freely.
- **The navigation** is in \`astro.config.mjs\`, rebuilt from the manifest on
  every eject. Reorder it there and the next \`--force\` will undo you.

## Regenerating

The pages under \`src/content/docs/\` are copies. Edit the code, then:

\`\`\`bash
glossic generate       # rewrites docs/ for whatever changed
glossic eject --force  # copies them back in here
\`\`\`

Anything you write by hand in a unit page is lost on the next eject. Change the
source and regenerate instead.

## Before deploying

Set \`site\` in \`astro.config.mjs\` to the URL the site will live at. Starlight
needs it to emit a sitemap, and skips it with a warning while it is missing.
`;

const gitignore = (): string => "node_modules/\ndist/\n.astro/\n";

const pnpmWorkspace = (): string =>
  `# Generated by \`glossic eject\`.
#
# This file is what makes the site its own pnpm workspace. Without it, a site
# inside a pnpm monorepo belongs to the outer workspace and \`pnpm install\` run
# from here installs nothing.
#
# It declares no packages because the site is one project, not a monorepo.
packages: []
`;

/** Every file of the scaffold, keyed by its path inside the output directory. */
export const templateFiles = (input: TemplateInput): Record<string, string> => ({
  "package.json"                 : packageJson(input),
  "astro.config.mjs"             : astroConfig(input),
  "src/content.config.ts"        : contentConfig(),
  [CUSTOM_CSS]                   : customCss(input.accent),
  "src/content/docs/index.mdx"   : landingPage(input),
  "README.md"                    : readme(input),
  ".gitignore"                   : gitignore(),
  "pnpm-workspace.yaml"          : pnpmWorkspace(),
});
