/** Teal. Deliberately not Starlight's purple, so an ejected site is not one more default. */
export const DEFAULT_ACCENT = "#0d9488";

const HEX = /^#?([0-9a-f]{3}|[0-9a-f]{6})$/i;

interface Hsl {
  h: number;
  s: number;
  l: number;
}

/** The accent palette Starlight reads, per theme. */
export interface AccentPalette {
  dark : { low: string; base: string; high: string };
  light: { low: string; base: string; high: string };
}

/** Accepts `#0d9488`, `0d9488` and `#0d9`, and returns the six-digit form. */
export const normaliseHex = (value: string): string | undefined => {
  const match = HEX.exec(value.trim());

  if (match === null) return undefined;

  const digits = (match[1] ?? "").toLowerCase();

  return `#${digits.length === 3 ? [...digits].map((d) => d + d).join("") : digits}`;
};

const toHsl = (hex: string): Hsl => {
  const r = Number.parseInt(hex.slice(1, 3), 16) / 255;
  const g = Number.parseInt(hex.slice(3, 5), 16) / 255;
  const b = Number.parseInt(hex.slice(5, 7), 16) / 255;

  const max   = Math.max(r, g, b);
  const min   = Math.min(r, g, b);
  const delta = max - min;
  const l     = (max + min) / 2;

  if (delta === 0) return { h: 0, s: 0, l };

  const s = delta / (1 - Math.abs(2 * l - 1));
  const h =
    max === r ? ((g - b) / delta) % 6
    : max === g ? (b - r) / delta + 2
    : (r - g) / delta + 4;

  return { h: (h * 60 + 360) % 360, s, l };
};

const toHex = ({ h, s, l }: Hsl): string => {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;

  const [r, g, b] =
    h < 60  ? [c, x, 0]
    : h < 120 ? [x, c, 0]
    : h < 180 ? [0, c, x]
    : h < 240 ? [0, x, c]
    : h < 300 ? [x, 0, c]
    : [c, 0, x];

  const channel = (value: number): string =>
    Math.round((value + m) * 255)
      .toString(16)
      .padStart(2, "0");

  return `#${channel(r ?? 0)}${channel(g ?? 0)}${channel(b ?? 0)}`;
};

const withLightness = (hex: string, l: number): string => {
  const hsl = toHsl(hex);

  return toHex({ ...hsl, l });
};

/**
 * The five shades Starlight wants from one colour. `low` is the quiet end and
 * `high` the loud one, and they swap places between themes: on a dark page the
 * loud shade has to be light, and on a light page dark.
 */
export const accentPalette = (accent: string): AccentPalette => ({
  dark: {
    low : withLightness(accent, 0.17),
    base: accent,
    high: withLightness(accent, 0.82),
  },
  light: {
    low : withLightness(accent, 0.88),
    base: withLightness(accent, 0.36),
    high: withLightness(accent, 0.22),
  },
});

/**
 * The one stylesheet the scaffold ships. Small on purpose: everything in it is
 * a Starlight variable, so a reader can change the look without learning how
 * the theme is built.
 */
export const customCss = (accent: string): string => {
  const palette = accentPalette(accent);

  return `/*
 * Generated by \`glossic eject\` from --accent ${accent}.
 * These are Starlight's own variables: change a value and the whole site
 * follows. https://starlight.astro.build/guides/css-and-tailwind/
 */
:root {
  --sl-color-accent-low : ${palette.dark.low};
  --sl-color-accent     : ${palette.dark.base};
  --sl-color-accent-high: ${palette.dark.high};
}

:root[data-theme="light"] {
  --sl-color-accent-low : ${palette.light.low};
  --sl-color-accent     : ${palette.light.base};
  --sl-color-accent-high: ${palette.light.high};
}
`;
};
